SchoolManagementSystem/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('adminoo/', include('adminoo.urls')),

]

adminoo/urls.py
# -*- coding:utf-8 -*-
"""
----------------------------------------------------------
作者: 武广辉
日期: 2022/4/19 14:43
----------------------------------------------------------
当前项目的名称: SchoolManagementSystem
在文件创建过程中在“新建文件”对话框中指定的新文件的名称: urls.py.py
当前集成开发环境: PyCharm
----------------------------------------------------------
"""
from django.urls import path, re_path
from adminoo import views

app_name = "adminoo"

urlpatterns = [
    path('register/', views.register),  # 注册功能
    path('register_user/', views.register_user),  # 注册功能
    path('login/', views.login),  # 登录功能
    path('logout/', views.logout),  # 注销功能
    path('add_profession/', views.add_profession),  # 添加出版社
    path('profession_list/', views.profession_list, name='profession_list'),  # 出版社列表
    path('profession_list/<int:page>', views.profession_list, name='profession_list'),  # 出版社列表(分页)
    path('update_profession/', views.update_profession, name='update_profession'),  # 修改出版社
    path('delete_profession/', views.delete_profession, name="delete_profession"),

    path('add_report/', views.add_report, name="add_report"),  # 添加上报信息
    path('add_report_userlogin/', views.add_report_userlogin, name="add_report_userlogin"),  # 添加上报信息
    path('add_report_userlogin/<int:card>', views.add_report_userlogin, name="add_report_userlogin"),  # 添加上报信息

    path('report_list/', views.report_list, name='report_list'),  # 上报列表
    path('report_list/<int:page>', views.report_list, name='report_list'),  # 带参数路由的上报列表（分页）

    path('update_report/', views.update_report, name='update_report'),  # 修改上报信息
    path('delete_report/', views.delete_report, name="delete_report"),

    path('add_teacher/', views.add_teacher, name="add_teacher"),  # 添加负责人
    path('teacher_list/', views.teacher_list, name='teacher_list'),  # 负责人列表
    path('teacher_list/<int:page>', views.teacher_list, name='teacher_list'),  # 负责人列表
    path('update_teacher/', views.update_teacher, name='update_teacher'),  # 修改出版社
    path('delete_teacher/', views.delete_teacher, name="delete_teacher"),

    path('add_user/', views.add_user, name="add_user"),  # 添加用户
    path('user_list/', views.user_list, name='user_list'),  # 用户列表
    path('user_list/<int:page>', views.user_list, name='user_list'),  # 带参数路由的用户列表（分页）
    path('update_user/', views.update_user, name='update_user'),  # 修改用户
    path('delete_user/', views.delete_user, name='delete_user'),  # 删除用户

    # path('index/', views.index, name='index'),  # 首页
    path('search/', views.search, name='search'),  # 查询

]

adminoo/models.py
from django.db import models

# Create your models here.


# 管理员数据模型
class Adminoo(models.Model):
    name = models.CharField(max_length=32, verbose_name="用户名")  # 图书管理员用户名
    nickname = models.CharField(max_length=32, verbose_name="昵称")  # 昵称
    password = models.CharField(max_length=32, verbose_name="密码")  # 密码


# 学院数据模型
class College(models.Model):
    name = models.CharField(max_length=32, verbose_name="学院名称", null=True, blank=True,)


# 专业数据模型
class Profession(models.Model):
    name = models.CharField(max_length=128, verbose_name="专业名称")  # 专业名称
    teacher = models.CharField(max_length=128, verbose_name="专业负责人")  # 专业负责人
    college = models.ForeignKey(to='College', on_delete=models.CASCADE, verbose_name="学院名称")


# 上报信息数据模型
class Report(models.Model):
    name = models.CharField(max_length=128, verbose_name="上报用户名")
    report_num = models.CharField(max_length=128, verbose_name="健康上报编码", null=True, blank=True)
    report_address = models.CharField(max_length=128, verbose_name="上报地址")
    card = models.CharField(max_length=32, null=True, blank=True, verbose_name="学生学号")
    report_age = models.CharField(max_length=128, verbose_name="上报年龄")
    report_phone = models.CharField(max_length=11, verbose_name="电话号码")  # 电话
    report_temperature = models.CharField(max_length=128, verbose_name="体温")
    report_description = models.TextField(verbose_name="身体状况")
    profession = models.ForeignKey(to='Profession', on_delete=models.CASCADE, verbose_name="专业名称")
    report_time = models.DateTimeField(auto_now=True, verbose_name="上报时间")    # 上报时间


class Image(models.Model):
    # 创建点数据表用来存储上传的照片路径和名称
    img_address = models.ImageField(verbose_name="图片路径")  # 图片路径 -->> 会将路径封装成一个对象，需要使用模块Pillow,python 3.6 后 使用 PIL 模块
    img_label = models.CharField(max_length=128, verbose_name="上报健康码")
    reports = models.ForeignKey(to='Report', on_delete=models.CASCADE, verbose_name="上报")  # 图书的图片


# 用户
class User(models.Model):
    name = models.CharField(max_length=32, verbose_name="用户名")
    nickname = models.CharField(max_length=32, verbose_name="用户昵称")
    sex = models.CharField(max_length=32, verbose_name="性别", default='男')
    card = models.CharField(max_length=32, null=True, blank=True, verbose_name="学生学号")
    password = models.CharField(max_length=32, verbose_name="密码")
    phone = models.CharField(max_length=11, verbose_name="电话号码")  # 电话
    time = models.DateTimeField(auto_now=True, verbose_name="时间")    # 每个用户登陆的时间
    profession = models.ForeignKey(to="Profession", on_delete=models.CASCADE, verbose_name="专业")   # 借的书进行绑定


class Teacher(models.Model):
    teacher_name = models.CharField(max_length=32, verbose_name="负责人姓名")
    teacher_card = models.CharField(max_length=32, null=True, blank=True, verbose_name="负责人工号")
    teacher_phone = models.CharField(max_length=11, null=True, blank=True, verbose_name="电话号码")  # 电话
    profession = models.ManyToManyField(to="Profession", verbose_name="专业", related_name='teacher_profession')   # 专业进行绑定

adminoo/views.py
from django.shortcuts import render

# Create your views here.
import hashlib
import time

from django.core.paginator import Paginator
from django.db.models import Q, Count
from faker import Faker
from django.db import connection
from django.shortcuts import render, redirect, HttpResponse

# Create your views here.
from adminoo import models


def pwd_encrypt(password):
    md5 = hashlib.md5()  # 获取md5对象
    md5.update(password.encode())  # 进行更新注意需要使用 字符串的二进制格式
    result = md5.hexdigest()  # 获取加密后的内容
    return result


# 注册视图函数
def register(request):
    if request.method == 'POST':
        # 1. 获取表单提交过来的内容
        username = request.POST.get('register_username')
        nickname = request.POST.get('register_nickname')
        password = request.POST.get('register_password')
        # 2.对密码进行加密
        password = pwd_encrypt(password)
        # 3. 保存到数据库
        models.User.objects.create(name=username, nickname=nickname, password=password)
        # 4. 重定向到登录界面
        return redirect('/adminoo/login')
    #
    return render(request, 'register_new.html')


def register_user(request):
    """注册用户"""
    if request.method == "GET":
        # 查询所有的
        profession_obj_list = models.Profession.objects.all()
        # 将页面转跳到用户添加页面，并把数据传给前端
        return render(request, "register_user.html", locals())

    else:
        # 获取表单提交过来的用户信息
        name = request.POST.get("register_username")
        nickname = request.POST.get("register_nickname")
        sex = request.POST.get("sex")
        card = request.POST.get("card")
        phone = request.POST.get("phone")
        time = request.POST.get("time")
        profession_id = request.POST.get("profession_id")
        profession_obj = models.Profession.objects.get(id=profession_id)  # 专业对象
        password = request.POST.get("register_password")
        # 对密码进行加密
        password = pwd_encrypt(password)
        # 将用户信息保存数据库中
        user_obj = models.User.objects.create(
            name=name,
            nickname=nickname,
            sex=sex,
            card=card,
            password=password,
            phone=phone,
            time=time,
            profession=profession_obj,
        )

        return redirect("/adminoo/login")
    return render(request, 'register_user.html')


def login(request):
    error_msg = ''
    if request.method == 'POST':
        # 1.获取表单提交过来的内容
        username = request.POST.get('login_username')
        pwd = request.POST.get('login_password')
        # 2. 对输入的密码进行加密
        pwd = pwd_encrypt(pwd)
        if username=="1":
            ret = models.Adminoo.objects.filter(name=username, password=pwd)
            if ret:
                # 有此用户 -->> 跳转到首页
                # 登录成功后，将用户名和昵称保存到session 中，
                request.session['username'] = username
                adminoo_obj = ret.last()  # 获取adminoo对象
                nickname = adminoo_obj.nickname
                request.session['nickname'] = nickname
                # 将用户的id 保存到session中
                request.session['id'] = adminoo_obj.id
                return render(request, 'profession_add.html')
            else:
                # 没有此用户-->> 用户名或者密码错误
                error_msg = '用户名或者密码错误请重新输入'
        else:
            # 3.数据库查询
            # select * from adminoo where name=username and password =pwd
            ret = models.User.objects.filter(name=username, password=pwd)
        # print(ret) # 如果用户不存在 返回空 QuerySet对象,转换成False
            if ret:
                # 有此用户 -->> 跳转到首页
                # 登录成功后，将用户名和昵称保存到session 中，
                request.session['username'] = username
                adminoo_obj = ret.last()  # 获取adminoo对象
                nickname = adminoo_obj.nickname
                request.session['nickname'] = nickname
                # 将用户的id 保存到session中
                request.session['id'] = adminoo_obj.id
                profession = models.Profession.objects.all()
                return render(request, 'base_user.html', {"profession": profession, "ret": ret})
                # return render(request, 'base_user.html', {'ret': ret})
                # return redirect('/adminoo/add_report_userlogin/', {"ret": ret})
            else:
                # 没有此用户-->> 用户名或者密码错误
                error_msg = '用户名或者密码错误请重新输入'
    return render(request, 'login_new.html', {'error_msg': error_msg})


# 登出
def logout(request):
    # 1. 将session中的用户名、昵称删除
    request.session.flush()
    # 2. 重定向到 登录界面
    return redirect('/adminoo/login/')


# 装饰器
def adminoo_decorator(func):
    def inner(request, *args, **kwargs):
        username = request.session.get('username')
        nickname = request.session.get('nickname')
        if username and nickname:
            """用户登录过"""
            return func(request, *args, **kwargs)
        else:
            """用户没有登录，重定向到登录页面"""
            return redirect('/adminoo/login/')

    return inner


# 专业操作
def add_profession(request):
    if request.method == "GET":
        # 获取内容
        # 从数据库中获取全部学院对象（有N条数据），然后返回到前端，通过for循环一一展示。
        college_list = models.College.objects.all()

        # 下面可以用这个：return redirect('/adminoo/profession_list/')
        # return redirect('adminoo:profession_list')
        return render(request, "profession_add.html", locals())
    elif request.method == "POST":
        profession_name = request.POST.get("profession_name")
        # profession_teacher = request.POST.get("profession_teacher")
        college_id = request.POST.get("college")  # 专业id
        college_obj = models.College.objects.get(id=college_id)  # 学院对象
        # 保存到数据库中
        models.Profession.objects.create(name=profession_name, college=college_obj, )
        return redirect('/adminoo/profession_list')


# @adminoo_decorator
def profession_list(request, page=1):
    """专业列表"""
    # 我们要把专业的数据库中的数据全部取出，传给前端进行显示
    # ----->方法init(列表,int)：返回分页对象，参数为列表数据，每面数据的条数
    #       属性count：返回对象总数
    #       属性num_pages：返回页面总数
    #       属性page_range：返回页码列表，从1开始，例如[1, 2, 3, 4]
    #       方法page(m)：返回Page对象，表示第m页的数据，下标以1开始
    if request.method == "GET":
        profession_obj_list = models.Profession.objects.all()  # 获取专业所有数据
        paginator = Paginator(profession_obj_list, 5)  # 对数据库中获取的数据进行分页，每页显示10条数据
        total_page_num = paginator.num_pages  # num_pages:总页码
        current_page_num = page if page else request.GET.get("page", 1)  # 当前页，默认显示第一页
        profession_page_objs = paginator.page(current_page_num)  # 获取当页面的数据对象，用于传到前端进行显示
        page_range = paginator.page_range  # 确定页面范围，以便进行模板渲染使用页码
        # 当前页
        # 由于每个页面只让显示10页，我们要判断，总页码是否大10页，如果总页码小于10页就直接显示。下面我们主要完成总页码大于10页的情况，我们要分情况处理。
        if total_page_num > 10:  # 当总页码大于10时
            if current_page_num < 9:  # 当前页小于10时
                page_range = range(1, 11)
            elif current_page_num + 8 > total_page_num:  # 当前页是倒数第8页时页码的范围
                page_range = range(current_page_num - 2, total_page_num + 1)
            else:
                page_range = range(current_page_num - 2, current_page_num + 8)  # 当前页大于8且小于倒数第8页时页码的范围
        else:  # 当页码小于10时
            page_range = page_range
        # Django笔记10：用local()代替视图函数中render的字典参数：https://blog.csdn.net/gaifuxi9518/article/details/88632972
        return render(request, "profession_list.html", locals())  # local()是Python中的一个内置函数，它可以将函数中的局部变量以字典的形式返回。
        # 等同于：return render(request,'profession_list.html', {'profession_page_objs': profession_page_objs})


def update_profession(request):
    """修改专业"""
    if request.method == "GET":
        profession_id = request.GET.get("id")
        # 2.从数据库中获取要修改的专业对象
        profession_obj = models.Profession.objects.get(id=profession_id)
        # profession = models.Profession.objects.get(id=profession_id)
        college_list = models.College.objects.all()
        return render(request, "profession_update.html", locals())
    else:
        # 1.获取report_list.html页面传过来的id
        profession_id = request.POST.get("id")
        # 2.从数据库中获取要修改的健康报告对象
        names = request.POST.get("name")
        # 3. 获取所有的专业数据,传到前端用来选择专业。
        college = request.POST.get("college")
        college_obj = models.College.objects.get(id=college)  # 专业对象
        # 将表单提交过来的数据保存到数据库
        profession_obj = models.Profession.objects.filter(id=profession_id).update(name=names, college=college_obj)
    return redirect('/adminoo/profession_list/')


def delete_profession(request):
    """删除专业"""
    # 获取profession_list.html页面传过来的id
    profession_id = request.GET.get('id')
    # 根据id，从数据库中获取专业对象
    profession = models.Profession.objects.get(id=profession_id)
    # 从数据库中删除该专业对象，并重定向到专业列表
    profession.delete()
    return redirect("/adminoo/profession_list/")


# @adminoo_decorator
def add_report(request):
    """添加健康报告"""
    if request.method == "GET":
        # TODO:添加性别，可以模仿上个项目的user_add
        # 从数据库中获取全部专业对象（有N条数据），然后返回到前端，通过for循环一一展示。
        profession_list = models.Profession.objects.all()
        # 将页面转调到添加健康报告的页面
        return render(request, "report_add.html", locals())
    elif request.method == "POST":
        f = Faker(locale="zh_CN")  # 初始化Faker对象
        report_num = f.msisdn()  # 健康报告编码
        # 获取report_add.html表单提交过来的数据
        report_name = request.POST.get("name")  # 上报人的姓名
        report_time = request.POST.get("report_time")  # 上报时间
        # teacher = request.POST.get("teacher")
        report_age = request.POST.get("report_age")
        card = request.POST.get("card")
        # report_price = request.POST.get("report_price")
        report_address = request.POST.get("report_address")
        report_phone = request.POST.get("report_phone")
        report_description = request.POST.get("report_description")
        report_temperature = request.POST.get("report_temperature")
        # comment_nums = request.POST.get("comment_nums")
        profession_id = request.POST.get("profession")  # 专业id
        profession_obj = models.Profession.objects.get(id=profession_id)  # 专业对象
        # 将表单获取到的数据保存到数据库中
        report_obj = models.Report.objects.create(

adminoo/templates/login_new.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{#    <link rel="stylesheet" href="../static/iconfont/iconfont.css">#}
    <link rel="stylesheet" href="{% static "../static/iconfont/iconfont.css"  %}">
    <link rel="stylesheet" href="{% static "../static/css/login-index.css" %}">
    <!--我们只需要更改这里的链接就可以，上面的incofont.css不用了-->
    <link rel="stylesheet" href="{% static "https://at.alicdn.com/t/font_3315218_7zvl76rufg3.css" %}">
    <style>
        /*更改输入框默认值的字体颜色*/
        input::-webkit-input-placeholder{
            color: burlywood;
        }

    </style>
    <title>Login</title>
</head>
<body>
<form method="post" autocomplete="off">
    {% csrf_token %}
<div class="login-box">
    <h1>登录</h1>
    <div class="input-box">
        <div class="input-text">
            <span class="iconfont icon-2yonghu"></span>
            <input type="text" placeholder="输入用户名" name="login_username" >
        </div>
{#        <div class="input-text">#}
{#            <span class="iconfont icon-xingxing"></span>#}
{#            <input type="text" placeholder="输入昵称" name="login_nickname" >#}
{#        </div>#}

        <div class="input-text">
            <span class="iconfont icon-dengluzhuce"></span>
            <input type="password" placeholder="输入密码" name="login_password">
        </div>
        <div class="error-msg">
            <p>{{ error_msg }}</p>
        </div>
        <div class="input-btn">
            <button type="submit">
              登录
            </button>

        </div>
        <div class="sign-up">
            <p class="text-muted mb-0">您没有有账户? <a href="/adminoo/register_user/">点击这里注册</a></p>
        </div>
    </div>
</div>


</form>

</body>
</html>

adminoo/templates/teacher_update.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="content-wrapper">
        <div class="container-fluid">


            <div class="row">
                <div class="col-lg-6">
                    <div class="card gradient-forest">
                        <div class="card-body">
                            <div class="card-title text-primary"><h4 style="text-align: center;color:white">修改负责人</h4>
                            </div>
                            <hr>
                            <form method="post" action="{% url "adminoo:update_teacher" %}">
                                {% csrf_token %}
                                    <input type="hidden" required
                                           class="form-control input-primary my-1"
                                           name="id" id="input-20" value="{{ teacher_obj.id }}">
                                <div class="form-group">
                                    <label for="input-20"
                                           style="color: white">姓名</label>
                                    <input type="text" required
                                           class="form-control input-primary my-1"
                                           name="teacher_name" id="input-20" value="{{ teacher_obj.teacher_name }}">
                                </div>
                                <div class="form-group">
                                    <label for="input-20"
                                           style="color: white">工号</label>
                                    <input type="text" required
                                           class="form-control input-primary my-1"
                                           name="teacher_card" id="input-20" value="{{ teacher_obj.teacher_card }}">
                                </div>
                                <div class="form-group">
                                    <label for="input-20"
                                           style="color: white">手机号</label>
                                    <input type="text" required
                                           class="form-control input-primary my-1"
                                           name="teacher_phone" id="input-20" value="{{ teacher_obj.teacher_phone }}">
                                </div>
                                <div class="form-group">
                                    <label for="input-20"
                                           style="color: white">负责专业</label>
                                    <select name="profession" required
                                            class="form-control input-primary my-1"
                                            id="input-20">
                                        {% for profession_obj in profession_obj_list %}
                                            <option value="{{ profession_obj.id }}">{{ profession_obj.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>

                                <div class="modal fade" id="modal-animation-9">
                                    <div class="modal-dialog">
                                        <div class="modal-content animated wobble">
                                            <div class="modal-header">
                                                <h5 class="modal-title">确认弹框</h5>
                                                <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <p>你确认修改这条数据吗？</p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-danger" data-dismiss="modal"><i
                                                        class="fa fa-times"></i> 关闭
                                                </button>
                                                <button type="submit" class="btn btn-success"><i
                                                        class="fa fa-check-square-o"></i> 修改
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button type="button"
                                            class="btn btn-primary btn-lg btn-block waves-effect waves-light m-1"
                                            data-toggle="modal" data-target="#modal-animation-9"><i
                                            class="zmdi zmdi-check-circle"></i>提交
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div><!--End Row-->
        </div>
        <!-- End container-fluid-->
    </div>
{% endblock %}

adminoo/templates/user_update.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="content-wrapper">
        <div class="container-fluid">

            <div class="row">


                <div class="col-lg-6">
                    <div class="card gradient-forest">
                        <div class="card-body">
                            <div class="card-title text-primary"><h4 style="text-align: center;color:white">修改用户</h4>
                            </div>
                            <hr>
                            <form action="{% url "adminoo:update_user" %}" method="post">
                                {% csrf_token %}


                                <input type="hidden" required
                                       class="form-control input-primary my-1"
                                       name="id" id="input-20" value="{{ user_obj.id }}">
                                <div class="form-group">
                                    <label for="input-20"
                                           style="color: white">用户名</label>
                                    <input type="text" required
                                           class="form-control input-danger my-1"
                                           name="name" id="input-20" value="{{ user_obj.name }}" disabled style="background: rgba(0,11,69,0.69)">
                                </div>
                                <div class="form-group">
                                    <label for="input-20"
                                           style="color: white">学号</label>
                                    <input type="text" required
                                           class="form-control input-danger my-1"
                                           name="card" id="input-20" value="{{ user_obj.card }}" disabled style="background: rgba(0,11,69,0.69)">
                                </div>
                                <div class="form-group">
                                    <label for="input-20"
                                           style="color: white">昵称</label>
                                    <input type="text" required
                                           class="form-control input-primary my-1"
                                           name="nickname" id="input-20" value="{{ user_obj.nickname }}">
                                </div>
                                <div class="form-group">
                                    <label for="input-20"
                                           style="color: white">密码</label>
                                    <input type="password" required
                                           class="form-control input-primary my-1"
                                           name="password" id="input-20" value="{{ user_obj.password }}">
                                </div>
                                <div class="form-group">
                                    <label for="input-20"
                                           style="color: white">电话号码</label>
                                    <input type="tel" required
                                           class="form-control input-primary my-1"
                                           name="phone" id="input-20" value="{{ user_obj.phone }}">
                                </div>
                                <div class="form-group">
                                    <label for="input-20"
                                           style="color: white">性别</label>
                                    <select name="sex" required
                                            class="form-control single-select input-primary my-1"
                                            id="input-20">
                                            <option value="男">男</option>
                                            <option value="女">女</option>

                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="input-20"
                                           style="color: white">专业</label>
                                    <select name="profession_id" required
                                            class="form-control input-primary my-1"
                                            id="input-20">
                                        {% for profession_obj in profession_obj_list %}
                                            <option value="{{ profession_obj.id }}">{{ profession_obj.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="modal fade" id="modal-animation-9">
                                    <div class="modal-dialog">
                                        <div class="modal-content animated wobble">
                                            <div class="modal-header">
                                                <h5 class="modal-title">确认弹框</h5>
                                                <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <p>你确认修改这条数据吗？</p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-danger" data-dismiss="modal"><i
                                                        class="fa fa-times"></i> 关闭
                                                </button>
                                                <button type="submit" class="btn btn-success"><i
                                                        class="fa fa-check-square-o"></i> 修改
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button type="button"
                                            class="btn btn-primary btn-lg btn-block waves-effect waves-light m-1"
                                            data-toggle="modal" data-target="#modal-animation-9"><i
                                            class="zmdi zmdi-check-circle"></i>提交
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div><!--End Row-->
        </div>
        <!-- End container-fluid-->

    </div>

{% endblock %}